#!/usr/bin/env python2.7
from JumpScale import j
import requests
import json
import time
import JumpScale.baselib.remote
publicip="??"
compute1_user="??"
compute1_pass="??"
controller_ip="??"
compute1_ip="??"
network_ip="??"
j.remote.fabric.setHost('%s@%s:2224'%(compute1_user, publicip,))
j.remote.fabric.setDefaultPasswd(compute1_pass, '%s@%s:2224'%(compute1_user, publicip))
j.remote.fabric.api.sudo('echo "compute1" > /etc/hostname')
j.remote.fabric.api.sudo('echo "auto eth1" >> /etc/network/interfaces')
j.remote.fabric.api.sudo('echo "iface eth1 inet static" >> /etc/network/interfaces')
j.remote.fabric.api.sudo('echo "\taddress 192.168.9.3" >> /etc/network/interfaces')
j.remote.fabric.api.sudo('echo "\tnetmask 255.255.255.0" >> /etc/network/interfaces')
j.remote.fabric.api.sudo('echo -e "%s\tcontroller" >> /etc/hosts'%(controller_ip,))
j.remote.fabric.api.sudo('echo -e "%s\tcompute1" >> /etc/hosts'%(compute1_ip,))
j.remote.fabric.api.sudo('echo -e "%s\tnetwork" >> /etc/hosts'%(network_ip,))
j.remote.fabric.api.sudo('apt-get install ntp -y')
j.remote.fabric.api.sudo('sed -i \'s/server/#server/\' /etc/ntp.conf')
j.remote.fabric.api.sudo('sed -i \'/#server ntp.ubuntu.com/a server controller\' /etc/ntp.conf')
j.remote.fabric.api.sudo('apt-get install python-software-properties -y')
j.remote.fabric.api.sudo('echo "deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/juno main" > /etc/apt/sources.list.d/ubuntu-cloud-archive-juno-trusty.list')
j.remote.fabric.api.sudo('apt-get install ubuntu-cloud-keyring -y')
j.remote.fabric.api.sudo('apt-get install debconf-utils -y')
j.remote.fabric.api.sudo('echo -e "grub\tgrub/update_grub_changeprompt_threeway\tselect\tinstall_new" | debconf-set-selections')
j.remote.fabric.api.sudo('echo -e "grub-legacy-ec2\tgrub/update_grub_changeprompt_threeway\tselect\tinstall_new" | debconf-set-selections')
j.remote.fabric.api.sudo('apt-get update -y && apt-get dist-upgrade')
j.remote.fabric.api.sudo('apt-get install nova-compute sysfsutils -y')
#####/etc/nova/nova.conf
#j.remote.fabric.api.sudo('sed -i \'/^\[DEFAULT\]/a rpc_backend = rabbit\' /etc/nova/nova.conf')
j.remote.fabric.api.sudo('sed -i \'/^\[DEFAULT\]/a rabbit_host = controller\' /etc/nova/nova.conf')
j.remote.fabric.api.sudo('sed -i \'/^\[DEFAULT\]/a rabbit_password = testpass\' /etc/nova/nova.conf')
j.remote.fabric.api.sudo('sed -i \'/^\[DEFAULT\]/a auth_strategy = keystone\' /etc/nova/nova.conf')
j.remote.fabric.api.sudo('sed -i \'/^\[DEFAULT\]/a my_ip = %s\' /etc/nova/nova.conf'%(compute1_ip,))
j.remote.fabric.api.sudo('sed -i \'/^\[DEFAULT\]/a vncserver_listen = 0.0.0.0\' /etc/nova/nova.conf')
j.remote.fabric.api.sudo('sed -i \'/^\[DEFAULT\]/a vncserver_proxyclient_address = %s\' /etc/nova/nova.conf'%(compute1_ip,))
j.remote.fabric.api.sudo('sed -i \'/^\[DEFAULT\]/a vnc_enabled = True\' /etc/nova/nova.conf')
j.remote.fabric.api.sudo('sed -i \'/^\[DEFAULT\]/a novncproxy_base_url = http://controller:6080/vnc_auto.html\' /etc/nova/nova.conf')
j.remote.fabric.api.sudo('echo "[keystone_authtoken]" >> /etc/nova/nova.conf')
j.remote.fabric.api.sudo('echo "auth_uri = http://controller:5000/v2.0" >> /etc/nova/nova.conf')
j.remote.fabric.api.sudo('echo "identity_uri = http://controller:35357" >> /etc/nova/nova.conf')
j.remote.fabric.api.sudo('echo "admin_tenant_name = service" >> /etc/nova/nova.conf')
j.remote.fabric.api.sudo('echo "admin_user = nova" >> /etc/nova/nova.conf')
j.remote.fabric.api.sudo('echo "admin_password = testpass" >> /etc/nova/nova.conf')
j.remote.fabric.api.sudo('echo "[glance]" >> /etc/nova/nova.conf')
j.remote.fabric.api.sudo('echo "host = controller" >> /etc/nova/nova.conf')
j.remote.fabric.api.sudo('service nova-compute restart')
j.remote.fabric.api.sudo('rm -f /var/lib/nova/nova.sqlite')
j.remote.fabric.api.sudo('echo "net.ipv4.conf.all.rp_filter=0" >> /etc/sysctl.conf')
j.remote.fabric.api.sudo('echo "net.ipv4.conf.default.rp_filter=0" >> /etc/sysctl.conf')
j.remote.fabric.api.sudo('sysctl -p')
j.remote.fabric.api.sudo('apt-get install neutron-plugin-ml2 neutron-plugin-openvswitch-agent -y')
j.remote.fabric.api.sudo('sed -i \'s/^connection/#connection/\' /etc/neutron/neutron.conf')
j.remote.fabric.api.sudo('sed -i \'/^\[DEFAULT\]/a rabbit_host = controller\' /etc/neutron/neutron.conf')
j.remote.fabric.api.sudo('sed -i \'/^\[DEFAULT\]/a rabbit_password = testpass\' /etc/neutron/neutron.conf')
j.remote.fabric.api.sudo('sed -i \'/^\[DEFAULT\]/a auth_strategy = keystone\' /etc/neutron/neutron.conf')
j.remote.fabric.api.sudo('sed -i \'s/^auth_uri/#auth_uri/\' /etc/neutron/neutron.conf')
j.remote.fabric.api.sudo('sed -i \'s/^admin_password/#admin_password/\' /etc/neutron/neutron.conf')
j.remote.fabric.api.sudo('sed -i \'s/^admin_user/#admin_user/\' /etc/neutron/neutron.conf')
j.remote.fabric.api.sudo('sed -i \'s/^admin_tenant_name/#admin_tenant_name/\' /etc/neutron/neutron.conf')
j.remote.fabric.api.sudo('sed -i \'s/^identity_uri/#identity_uri/\' /etc/neutron/neutron.conf')
j.remote.fabric.api.sudo('sed -i \'/^\[keystone_authtoken\]/a admin_password = testpass\' /etc/neutron/neutron.conf')
j.remote.fabric.api.sudo('sed -i \'/^\[keystone_authtoken\]/a admin_user = neutron\' /etc/neutron/neutron.conf')
j.remote.fabric.api.sudo('sed -i \'/^\[keystone_authtoken\]/a admin_tenant_name = service\' /etc/neutron/neutron.conf')
j.remote.fabric.api.sudo('sed -i \'/^\[keystone_authtoken\]/a identity_uri = http://controller:35357\' /etc/neutron/neutron.conf')
j.remote.fabric.api.sudo('sed -i \'/^\[keystone_authtoken\]/a auth_uri = http://controller:5000/v2.0\' /etc/neutron/neutron.conf')
j.remote.fabric.api.sudo('sed -i \'s/^core_plugin/#core_plugin/\' /etc/neutron/neutron.conf')
j.remote.fabric.api.sudo('sed -i \'/^\[DEFAULT\]/a core_plugin = ml2\' /etc/neutron/neutron.conf')
j.remote.fabric.api.sudo('sed -i \'/^\[DEFAULT\]/a service_plugins = router\' /etc/neutron/neutron.conf')
j.remote.fabric.api.sudo('sed -i \'/^\[DEFAULT\]/a allow_overlapping_ips = True\' /etc/neutron/neutron.conf')
######another config file /etc/neutron/plugins/ml2/ml2_conf.ini
j.remote.fabric.api.sudo('sed -i \'/^\[ml2\]/a type_drivers = flat,gre \' /etc/neutron/plugins/ml2/ml2_conf.ini')
j.remote.fabric.api.sudo('sed -i \'/^\[ml2\]/a tenant_network_types = gre \' /etc/neutron/plugins/ml2/ml2_conf.ini')
j.remote.fabric.api.sudo('sed -i \'/^\[ml2\]/a mechanism_drivers = openvswitch \' /etc/neutron/plugins/ml2/ml2_conf.ini')
j.remote.fabric.api.sudo('sed -i \'/^\[ml2_type_gre\]/a tunnel_id_ranges = 1:1000 \' /etc/neutron/plugins/ml2/ml2_conf.ini')
j.remote.fabric.api.sudo('sed -i \'/^\[securitygroup\]/a enable_security_group = True\' /etc/neutron/plugins/ml2/ml2_conf.ini')
j.remote.fabric.api.sudo('sed -i \'/^\[securitygroup\]/a enable_ipset = True \' /etc/neutron/plugins/ml2/ml2_conf.ini')
j.remote.fabric.api.sudo('sed -i \'/^\[securitygroup\]/a firewall_driver = neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver\' /etc/neutron/plugins/ml2/ml2_conf.ini')
j.remote.fabric.api.sudo('echo "[ovs]" >> /etc/neutron/plugins/ml2/ml2_conf.ini')
j.remote.fabric.api.sudo('echo "local_ip = 192.168.9.3" >> /etc/neutron/plugins/ml2/ml2_conf.ini')
j.remote.fabric.api.sudo('echo "tunnel_type = gre" >> /etc/neutron/plugins/ml2/ml2_conf.ini')
j.remote.fabric.api.sudo('echo "enable_tunneling = True" >> /etc/neutron/plugins/ml2/ml2_conf.ini')
j.remote.fabric.api.sudo('service openvswitch-switch restart')
################another file /etc/nova/nova.conf
j.remote.fabric.api.sudo('sed -i \'/^\[DEFAULT\]/a network_api_class = nova.network.neutronv2.api.API\' /etc/nova/nova.conf')
j.remote.fabric.api.sudo('sed -i \'/^\[DEFAULT\]/a security_group_api = neutron\' /etc/nova/nova.conf')
j.remote.fabric.api.sudo('sed -i \'/^\[DEFAULT\]/a linuxnet_interface_driver = nova.network.linux_net.LinuxOVSInterfaceDriver\' /etc/nova/nova.conf')
#j.remote.fabric.api.sudo('sed -i \'/^\[DEFAULT\]/a firewall_driver = nova.virt.firewall.NoopFirewallDriver\' /etc/nova/nova.conf')
j.remote.fabric.api.sudo('echo "[neutron]" >> /etc/nova/nova.conf')
j.remote.fabric.api.sudo('echo "url = http://controller:9696" >> /etc/nova/nova.conf')
j.remote.fabric.api.sudo('echo "auth_strategy = keystone" >> /etc/nova/nova.conf')
j.remote.fabric.api.sudo('echo "admin_auth_url = http://controller:35357/v2.0" >> /etc/nova/nova.conf')
j.remote.fabric.api.sudo('echo "admin_tenant_name = service" >> /etc/nova/nova.conf')
j.remote.fabric.api.sudo('echo "admin_username = neutron" >> /etc/nova/nova.conf')
j.remote.fabric.api.sudo('echo "admin_password = testpass" >> /etc/nova/nova.conf')
j.remote.fabric.api.sudo('service nova-compute restart')
j.remote.fabric.api.sudo('service neutron-plugin-openvswitch-agent restart')
